//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RinascitaWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyTelemetry
    {
        public decimal ID { get; set; }
        public string deviceid { get; set; }
        public string IdProcess { get; set; }
        public string Latitude { get; set; }
        public string N { get; set; }
        public string Longitude { get; set; }
        public string E { get; set; }
        public string month { get; set; }
        public string day { get; set; }
        public string year { get; set; }
        public string hhMMss { get; set; }
        public string speed { get; set; }
        public string altitude { get; set; }
        public string satellites { get; set; }
        public string hdop { get; set; }
        public string roll { get; set; }
        public string pitch { get; set; }
        public string Xg { get; set; }
        public string Yg { get; set; }
        public string Zg { get; set; }
        public string Audio { get; set; }
        public string Distance { get; set; }
        public string TempExt { get; set; }
        public string TempTyre { get; set; }
        public string FrontAbsorber { get; set; }
        public string BackAbsorber { get; set; }
        public Nullable<System.DateTime> DT_INS { get; set; }
    }
}
