//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RinascitaWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_pagesecurity
    {
        public decimal Id { get; set; }
        public string LevelGroup { get; set; }
        public string pagename { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> DT_INS { get; set; }
        public Nullable<System.DateTime> DT_UPD { get; set; }
    }
}
