//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RinascitaWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_users
    {
        public decimal Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string GroupLevel { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<System.DateTime> DT_INS { get; set; }
        public Nullable<System.DateTime> DT_UPD { get; set; }
        public string note { get; set; }
        public string mobile { get; set; }
        public string phone { get; set; }
    }
}
